create table if not exists public.cppem_phone_registry (
  id bigint generated by default as identity primary key,
  number_e164 text not null unique check (number_e164 ~ '^55[0-9]{10,11}$'),
  label text not null check (char_length(label) between 2 and 80),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cppem_phone_registry enable row level security;

drop policy if exists "Consulta pública de números ativos" on public.cppem_phone_registry;
create policy "Consulta pública de números ativos"
on public.cppem_phone_registry for select
to anon, authenticated
using (active = true);

insert into public.cppem_phone_registry (number_e164, label, active) values
  ('558194458120', 'CPPEM Marketing', true),
  ('558195460966', 'Pedagógico CPPEM', true),
  ('558195881908', 'Emilly CPPEM', true)
on conflict (number_e164) do update
set label = excluded.label, active = excluded.active, updated_at = now();

grant select on public.cppem_phone_registry to anon, authenticated;
